### ISSUE TITLE
Multiple kids and the ui helpers

### ISSUE THREAD

**Issue by SentinelCQ** [ccpk1/kidschores-ha-dashboard#8]
Took me a bit to get the setup correctly for 2 kids in my configuration.yaml.

Including it here in case someone else is having the same issue.
I have them named kid1/Kid1 and kid2/Kid2 below. 

Tricky part for me was knowing which parts to copy. Might be good to include a commented out section showing where to duplicate. I did the input select as an example below, but not the action. 

```
input_select:
  kc_kid1_chore_list:
    name: Kid1's Chore List
    options:
      - "None"
  kc_kid2_chore_list:
    name: Kid2's Chore List
    options:
      - "None"
#  kc_kid3_chore_list:
#    name: Kid3's Chore List
#    options:
#     - "None"

input_datetime:
  kc_ui_set_date_helper:
    name: Set Chore Date
    has_date: true
    has_time: true

automation:
  - alias: "Update KidsChore UI Helpers"
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: time_pattern
        minutes: "/5"
    action:
      - action: input_select.set_options
        data:
          entity_id: input_select.kc_kid1_chore_list
          options: >
            {% set chore_names = states.sensor 
              | selectattr('entity_id', 'search', 'sensor.kc_kid2_chore_status') 
              | selectattr('attributes.friendly_name', 'defined') 
              | map(attribute='attributes.friendly_name') 
              | list %}
            {% set chore_names = chore_names | map('regex_replace', '^.* - ', '') | list %}
            {{ ['None'] + chore_names if chore_names else ['None', 'No Chores Found'] }}
      - action: input_select.set_options
        data:
          entity_id: input_select.kc_kid2_chore_list
          options: >
            {% set chore_names = states.sensor 
              | selectattr('entity_id', 'search', 'sensor.kc_kid1_chore_status') 
              | selectattr('attributes.friendly_name', 'defined') 
              | map(attribute='attributes.friendly_name') 
              | list %}
            {% set chore_names = chore_names | map('regex_replace', '^.* - ', '') | list %}
            {{ ['None'] + chore_names if chore_names else ['None', 'No Chores Found'] }}

      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.kc_ui_set_date_helper
        data:
          datetime: "{{ (now().replace(hour=23, minute=0, second=0, microsecond=0) + timedelta(days=1)).isoformat() }}"

```
